object Versions {
    const val appCompat = "1.3.0"
    const val core = "1.2.0"
    const val constraintLayout = "1.1.3"
    const val compose = "1.0.3"
    const val composeConstraint = "1.0.0-beta02"
    const val coil = "1.4.0"
    const val dagger = "2.38.1"
    const val fragment = "1.2.4"
    const val gradlePlugin = "7.0.2"
    const val jUnit = "4.12"
    const val kotlin = "1.5.30"
    const val material = "1.3.0"
    const val okhttp = "4.9.0"
    const val paging = "3.0.1"
    const val pagingCompose = "1.0.0-alpha13"
    const val retrofit = "2.9.0"
    const val viewmodel = "2.2.0"

}